language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

env:
  - TOX_ENV=django11
  - TOX_ENV=django20
  - TOX_ENV=django21
  - TOX_ENV=django22
  - TOX_ENV=coverage

install:
  - pip install tox 

script:
  - tox -e $TOX_ENV

matrix:
  exclude:
   - python: "3.4"
     env: TOX_ENV=coverage
   - python: "3.5"
     env: TOX_ENV=coverage
